# Generated by Django 3.0.7 on 2021-06-09 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_title', models.CharField(max_length=1000)),
                ('event_date', models.DateField()),
                ('event_location', models.CharField(max_length=1000)),
                ('event_photo', models.FileField(upload_to='Event_photos/')),
                ('event_info', models.TextField()),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ExpertTeachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('experties', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
