# Generated by Django 3.0.7 on 2021-06-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertteachers',
            name='photo',
            field=models.FileField(default=1, upload_to='Staff_photos/'),
            preserve_default=False,
        ),
    ]
