# Generated by Django 3.0.7 on 2021-06-11 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_site_app', '0002_expertteachers_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_date', models.DateField()),
                ('event_title', models.CharField(max_length=500)),
                ('event_info', models.TextField()),
            ],
        ),
    ]
