# Generated by Django 3.0.7 on 2021-06-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site_app', '0003_upcomingevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingevent',
            name='event_poster',
            field=models.FileField(default=1, upload_to='Event_poster/'),
            preserve_default=False,
        ),
    ]
