# Generated by Django 3.0.7 on 2021-06-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='admission_std',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='bus_route_num',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='bus_stop',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='dob',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='emargency_contact',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='family_members',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='family_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='father_age',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='father_designation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='father_education',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='father_father_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='father_income',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='father_mobile',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='father_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='father_surname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='father_telephone',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='father_work_and_addr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='mother_age',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='mother_designation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='mother_education',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='mother_father_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='mother_income',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='mother_mobile',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='mother_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='mother_surname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='mother_telephone',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='mother_work_and_addr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='sibling1_age',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='sibling1_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='sibling1_school',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='sibling2_age',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='sibling2_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='sibling2_school',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='siblings',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='single_parent',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='student_allergies',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='student_alments',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='student_blood_group',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='student_caste',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='student_category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='student_close_landmark',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='student_father_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='student_gender',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='student_home_time',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='student_id_mark',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='student_known_lang',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='student_mobile',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='student_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='student_present_addr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='student_previous_class',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='student_previous_medium',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='student_previous_school',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='student_religion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='student_surname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='student_telephone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
