# Generated by Django 3.0.7 on 2021-06-08 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_app', '0003_auto_20210606_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprimaryadmissionformdetails',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 8, 15, 27, 14, 638991)),
        ),
    ]
