# Generated by Django 3.0.7 on 2021-06-08 15:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('admission_app', '0004_storeprimaryadmissionformdetails_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 8, 15, 39, 15, 277305, tzinfo=utc)),
        ),
    ]
