# Generated by Django 3.0.7 on 2021-06-08 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admission_app', '0005_auto_20210608_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeprimaryadmissionformdetails',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
