# Generated by Django 3.0.7 on 2021-06-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_app', '0006_auto_20210608_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprimaryadmissionformdetails',
            name='form_type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
